name: CrystamaeHistoria
author: Sefiraat
description: 黏液科技附加 水晶編年史 繁體翻譯版.
main: io.github.sefiraat.crystamaehistoria.CrystamaeHistoria
website: https://github.com/Sefiraat/CrystamaeHistoria
version: ${project.version}
api-version: 1.17
depend:
  - Slimefun
softdepend:
  - mcMMO
  - SlimeTinker
  - ExoticGarden
  - HeadLimiter
  - RoseStacker
  - WildStacker
  - Netheopoiesis
commands:
  crystamaehistoria:
    description: /historia
    usage: /historia <sub>
    aliases: [ ch, hist ]